
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jan 15 2026 20:13:00 -03 (Jan 15 2026 23:13:00 UTC)

// Verification Directory fv/topo 

module topo(clk, rst);
  input clk, rst;
  wire clk, rst;
endmodule

